- name: setup external interface as trunk port
  template: src=external_port.j2
            dest=/etc/network/interfaces.d/external_port
  become: yes
  register: external_port_cfg

- name: bring up external port
  shell: /sbin/ifconfig {{ external_port }} up
  become: yes
  when: external_port_cfg.changed
